import React from 'react'

const Body = () => (
    <div className={'content'}>
        <h2>Lorem Ipsum</h2>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque aliquam laoreet fringilla. Fusce ultrices leo eget risus auctor, id egestas lorem ullamcorper. Phasellus eget tempor velit. Duis id facilisis purus. Sed vel quam elit. Proin consectetur magna eget quam consequat luctus. Vivamus accumsan ipsum mauris, vestibulum volutpat dolor auctor eu. Quisque lobortis eget tellus id laoreet. Aenean a nibh laoreet, vestibulum justo eu, viverra nibh. Nam sed nisl ipsum. Curabitur at pulvinar felis. Maecenas a congue tellus. Ut sit amet lacinia augue, ut sodales erat. Suspendisse dapibus ultrices placerat.

        Praesent malesuada finibus dui eu cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut vulputate ex quis est venenatis porta. Donec purus ipsum, condimentum eu turpis sit amet, aliquet tempor quam. Aenean aliquam consequat mauris non condimentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque enim erat, dictum in tellus ut, auctor viverra felis. Vivamus facilisis nec orci et blandit. Ut volutpat, ipsum eget tempor accumsan, augue erat pellentesque odio, sed fringilla leo nibh vel eros. Aliquam non sollicitudin orci, sit amet iaculis neque. Etiam nisl nibh, cursus ac libero volutpat, elementum scelerisque risus. Praesent tincidunt metus at finibus fringilla. Suspendisse sed iaculis neque.

        Cras pulvinar, felis vitae pretium hendrerit, felis neque finibus turpis, at viverra mauris nulla in felis. In finibus sapien nec mollis consectetur. Aliquam erat volutpat. Sed interdum rutrum dolor, id condimentum ante facilisis sed. Etiam aliquet orci eu felis malesuada pulvinar. Duis dignissim turpis in aliquam sollicitudin. Curabitur scelerisque tincidunt purus, sit amet tincidunt magna pretium vitae. Phasellus eget justo malesuada, imperdiet metus eget, euismod odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin volutpat blandit ultricies. Morbi commodo sapien et tincidunt interdum. Sed eu eleifend felis. Nullam congue quam vitae sem sagittis, nec gravida sem placerat. Phasellus efficitur leo odio, in egestas erat dapibus sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

        Phasellus rhoncus nisi sem, eu vehicula nisl hendrerit sit amet. Nam laoreet, ante vitae sodales sagittis, nibh tortor luctus ante, non faucibus eros tortor sed libero. Nullam sed nisi aliquet, placerat mi id, elementum lectus. Quisque magna nunc, pretium id gravida et, vulputate a enim. Curabitur nisi sem, dictum sed libero quis, pharetra consectetur sem. Praesent lorem diam, rhoncus id commodo a, fringilla efficitur erat. Nunc euismod imperdiet purus, et eleifend ipsum egestas nec. Maecenas feugiat auctor velit id scelerisque. Cras ut laoreet risus. Quisque dignissim leo sit amet lorem rutrum, id maximus ligula vestibulum. Praesent vitae porttitor nibh. Fusce sollicitudin vel orci in egestas. Proin a est eleifend, ultrices turpis nec, aliquet sem.

        Pellentesque ac mauris a nisl lobortis sodales. Nunc elit nunc, viverra vel ipsum eget, venenatis vestibulum diam. Cras eget odio nec sapien tempus interdum. Aenean porttitor fermentum quam, et lobortis nulla dignissim eu. Sed quis commodo nibh. Curabitur id justo id arcu rutrum vehicula in vitae nunc. Nulla ultrices nisi vel massa varius, accumsan pellentesque ipsum semper. Maecenas eget tortor semper, consequat quam id, vehicula tortor. Pellentesque egestas et ipsum vel feugiat. Quisque non erat nisl. Proin suscipit, mi a egestas egestas, erat mauris euismod justo, eget convallis purus justo nec nisl. Integer vulputate, dui vitae placerat tempor, purus felis egestas nunc, at mattis elit urna id ligula.

        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque aliquam laoreet fringilla. Fusce ultrices leo eget risus auctor, id egestas lorem ullamcorper. Phasellus eget tempor velit. Duis id facilisis purus. Sed vel quam elit. Proin consectetur magna eget quam consequat luctus. Vivamus accumsan ipsum mauris, vestibulum volutpat dolor auctor eu. Quisque lobortis eget tellus id laoreet. Aenean a nibh laoreet, vestibulum justo eu, viverra nibh. Nam sed nisl ipsum. Curabitur at pulvinar felis. Maecenas a congue tellus. Ut sit amet lacinia augue, ut sodales erat. Suspendisse dapibus ultrices placerat.

        Praesent malesuada finibus dui eu cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut vulputate ex quis est venenatis porta. Donec purus ipsum, condimentum eu turpis sit amet, aliquet tempor quam. Aenean aliquam consequat mauris non condimentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque enim erat, dictum in tellus ut, auctor viverra felis. Vivamus facilisis nec orci et blandit. Ut volutpat, ipsum eget tempor accumsan, augue erat pellentesque odio, sed fringilla leo nibh vel eros. Aliquam non sollicitudin orci, sit amet iaculis neque. Etiam nisl nibh, cursus ac libero volutpat, elementum scelerisque risus. Praesent tincidunt metus at finibus fringilla. Suspendisse sed iaculis neque.

        Cras pulvinar, felis vitae pretium hendrerit, felis neque finibus turpis, at viverra mauris nulla in felis. In finibus sapien nec mollis consectetur. Aliquam erat volutpat. Sed interdum rutrum dolor, id condimentum ante facilisis sed. Etiam aliquet orci eu felis malesuada pulvinar. Duis dignissim turpis in aliquam sollicitudin. Curabitur scelerisque tincidunt purus, sit amet tincidunt magna pretium vitae. Phasellus eget justo malesuada, imperdiet metus eget, euismod odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin volutpat blandit ultricies. Morbi commodo sapien et tincidunt interdum. Sed eu eleifend felis. Nullam congue quam vitae sem sagittis, nec gravida sem placerat. Phasellus efficitur leo odio, in egestas erat dapibus sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

        Phasellus rhoncus nisi sem, eu vehicula nisl hendrerit sit amet. Nam laoreet, ante vitae sodales sagittis, nibh tortor luctus ante, non faucibus eros tortor sed libero. Nullam sed nisi aliquet, placerat mi id, elementum lectus. Quisque magna nunc, pretium id gravida et, vulputate a enim. Curabitur nisi sem, dictum sed libero quis, pharetra consectetur sem. Praesent lorem diam, rhoncus id commodo a, fringilla efficitur erat. Nunc euismod imperdiet purus, et eleifend ipsum egestas nec. Maecenas feugiat auctor velit id scelerisque. Cras ut laoreet risus. Quisque dignissim leo sit amet lorem rutrum, id maximus ligula vestibulum. Praesent vitae porttitor nibh. Fusce sollicitudin vel orci in egestas. Proin a est eleifend, ultrices turpis nec, aliquet sem.

        Pellentesque ac mauris a nisl lobortis sodales. Nunc elit nunc, viverra vel ipsum eget, venenatis vestibulum diam. Cras eget odio nec sapien tempus interdum. Aenean porttitor fermentum quam, et lobortis nulla dignissim eu. Sed quis commodo nibh. Curabitur id justo id arcu rutrum vehicula in vitae nunc. Nulla ultrices nisi vel massa varius, accumsan pellentesque ipsum semper. Maecenas eget tortor semper, consequat quam id, vehicula tortor. Pellentesque egestas et ipsum vel feugiat. Quisque non erat nisl. Proin suscipit, mi a egestas egestas, erat mauris euismod justo, eget convallis purus justo nec nisl. Integer vulputate, dui vitae placerat tempor, purus felis egestas nunc, at mattis elit urna id ligula.
    </div>
)

export default Body